version: '3'

volumes: 
  mongo:

services:
  db: 
    image: mongo
    container_name: db 
    volumes: 
      - mongo:/data/db
  front:
    build: ./front/.
    container_name: front
    ports:
      - 80:80
  back:
    build: ./back/.
    container_name: back
    environment:
      - PORT=8080
      - MONGO_HOST=db
    ports:
      - 8080:8080

