version: '3'

volumes: 
  ms-db:

services:
  mongo: 
    image: mongo
    container_name: mongo
    volumes: 
      - ms-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongo
  front:
    build: ./front/.
    container_name: front
    ports:
      - 80:80
    environment:
      - API_URL=${API_URL}:${API_PORT}
  back:
    build: ./back/.
    container_name: back
    depends_on:
      - mongo
    environment:
      - PORT=${API_PORT}
      - MONGO_HOST=mongo
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 3000:3000

