version: '3'

volumes: 
  mongo:

services:
  mongo: 
    image: mongo
    container_name: db 
    volumes: 
      - mongo:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
  front:
    build: ./front/.
    container_name: front
    ports:
      - 80:80
  back:
    build: ./back/.
    container_name: back
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGO_HOST=mongo
    ports:
      - 3000:3000

